### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by jkteske** [tomlouden/SPIDERMAN#32]
I just tried to install SPIDERMAN from the GitHub version, but get the following error. Is this a python version issue? 

sudo python setup.py install
Password:
/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running install
/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing spiderman_package.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/Users/jteske/Documents/GitHub/SPIDERMAN/setup.py", line 9, in <module>
    setup(      name='spiderman-package', 
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 156, in run
    self.run_command("egg_info")
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 301, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 665, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 1136, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 198, in write_pkg_file
    write_field('License', rfc822_escape(license))
  File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/util.py", line 518, in rfc822_escape
    lines = header.split('\n')
AttributeError: 'list' object has no attribute 'split'

**Comment by arjunsavel** [comment]
@jkteske I was able to fix this by cloning the repository, removing the `license` field from the setup.py file, and running `python setup.py install`. This may work for you as well — but I tried a couple fixes at the same time, so no promises!
